#application-dev.yml
server:
  port: 8001

spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos服务地址
  redis:
    host: 192.168.9.130 #Redis服务器地址
    port: 6379          #Redis服务器连接端口
    database: 0         #Redis数据库索引（默认为0）
    timeout: 1800000    #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接

ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)

#    hikari:
#      connection-test-query: SELECT 1
#      connection-timeout: 60000
#      idle-timeout: 500000
#      max-lifetime: 540000
#      maximum-pool-size: 12
#      minimum-idle: 10
#      pool-name: GuliHikariPool
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:src/main/resources/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:com/geek/eduservice/mapper/xml/*.xml

logging:
  level:
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
feign:
  hystrix:
    enabled: true  #开启熔断机制
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000  # 设置hystrix超时时间 默认1000ms

