server:
  port: 10001
spring:
  application:
    name: canal.client
  profiles:
    active: dev  # 环境设置：dev、test、prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql数据库链接
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 123456
