def git_auth = "47603b91-4a76-4b71-a19d-800f13049567"

def git_url = "git@gitee.com:lambertee/guli_edu.git"

node{
    stage('pull project'){
        checkout([$class: 'GitSCM', branches: [[name: "*/${branch}"]], extensions: [], userRemoteConfigs: [[credentialsId: "${git_auth}", url: "${git_url}"]]])
    }
    stage('编译，构建镜像') {

        sh "mvn -f guli_edu/common clean install"

        sh "mvn -f guli_edu/api_gateway clean package"

        sh "mvn -f guli_edu/service/${project_name} clean package"
    }
}
