# 服务端口
server:
  port: 8003
# 服务名
spring:
  application:
    name: service-vod
#环境设置：dev、test、prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB #最大上传单个文件大小 默认1M
      max-request-size: 1024MB  #最大置总上传的数据大小 默认10M
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos服务地址

#阿里云
aliyun:
  vod:
    file:
      keyid: LTAI5tPvpheNZzHZqu2Htgko
      keysecret: T18RmuOTonkTn7oyzGoUCrgIqWx28v

logging:
  level:
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN