server:
  port: 8002
spring:
  application:
    name: service-oss
  #开发环境设置
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos服务地址

aliyun:
  oss:
    file:
      enpoint: oss-cn-shenzhen.aliyuncs.com
      keyid: LTAI5tPvpheNZzHZqu2Htgko
      keysecret: T18RmuOTonkTn7oyzGoUCrgIqWx28v
      bucketname: guli-file--upload

logging:
  level:
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN